// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC45h_Wqa1f7GzeU2p9uzd3ZAA3gsbWiJs',
    appId: '1:501027624770:web:c19fe132d94cb59cc41adb',
    messagingSenderId: '501027624770',
    projectId: 'smart-v2v-communication-16be2',
    authDomain: 'smart-v2v-communication-16be2.firebaseapp.com',
    storageBucket: 'smart-v2v-communication-16be2.firebasestorage.app',
    measurementId: 'G-DQ6JMX5194',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu64oBeiVLHcuZ2JyuhRGc3FSX6MR-U8w',
    appId: '1:501027624770:android:21b956d96b1b642bc41adb',
    messagingSenderId: '501027624770',
    projectId: 'smart-v2v-communication-16be2',
    storageBucket: 'smart-v2v-communication-16be2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwU8K9ZIWumgQaCJafpz9SZ9rKRL4SVJI',
    appId: '1:501027624770:ios:658254ee0254771ec41adb',
    messagingSenderId: '501027624770',
    projectId: 'smart-v2v-communication-16be2',
    storageBucket: 'smart-v2v-communication-16be2.firebasestorage.app',
    iosBundleId: 'com.example.v2vApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwU8K9ZIWumgQaCJafpz9SZ9rKRL4SVJI',
    appId: '1:501027624770:ios:658254ee0254771ec41adb',
    messagingSenderId: '501027624770',
    projectId: 'smart-v2v-communication-16be2',
    storageBucket: 'smart-v2v-communication-16be2.firebasestorage.app',
    iosBundleId: 'com.example.v2vApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC45h_Wqa1f7GzeU2p9uzd3ZAA3gsbWiJs',
    appId: '1:501027624770:web:334fc91edd55ffd0c41adb',
    messagingSenderId: '501027624770',
    projectId: 'smart-v2v-communication-16be2',
    authDomain: 'smart-v2v-communication-16be2.firebaseapp.com',
    storageBucket: 'smart-v2v-communication-16be2.firebasestorage.app',
    measurementId: 'G-XELG813XY0',
  );
}
